# Generated by Django 5.0.3 on 2026-04-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('localizacion', models.CharField(max_length=300, verbose_name='Localizacion')),
                ('limite_usuarios', models.IntegerField(blank=True, default=1, null=True, verbose_name='Limite de usuarios')),
                ('duracion_minutos', models.IntegerField(blank=True, null=True, verbose_name='Duracion')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por', to='user.user')),
            ],
        ),
    ]
