# Generated by Django 5.0.3 on 2026-04-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuentros', '0001_initial'),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='tipo_mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascota_permitida', to='mascotas.tipomascota'),
        ),
    ]
